---
title: "Seminar Introduction"
format: html
toc: true
editor: source
---
## Session Overview

Welcome to the Doctoral Urban Planning Seminar! During our introductory session, we'll spend some time discussing our shared agenda for the semester. We will also discuss your individual goals and things you'd like to accomplish during the seminar.

## Before we Meet

- Please familiarize yourself with this website including the [seminar information](../syllabus/syllabus.qmd) section and [schedule](schedule.qmd).

- Read the following chapters from [*Grant Writing from the Ground Up*](https://i-share-uiu.primo.exlibrisgroup.com/permalink/01CARLI_UIU/gpjosq/alma99955035854905899)^[File access requires log in to University of Illinois Box.]
  - Chapter 2: [Finding What Fuels You](https://uofi.box.com/s/01sbk14fso0lmxqkdf84iv20suv7br26)
  - Chapter 3: [Identifying Stakeholders](https://uofi.box.com/s/0s1rh0x42so5pbxunivgvotejuzfbjta)
- Read a *funded* proposal - this could be a proposal submitted by a fellow student or a faculty member. Be prepared to share your reactions.

## After we Meet

- Spend 15 minutes identifying problem(s) you care enough about to "fight" to solve them. What do you want to do about it.

- For the problems you identified, score each problem based upon it's financial benefit, health benefit, academic benefit, security benefit, and ecological benefit. Bring your problem descriptions and totals to our initial seminar session.

## Slides

```{=html}
<iframe class="slide-deck" src="slides/Week_01/Week_01.html" height="100%" width="100%" frameBorder="0" style="min-height: 560px;"></iframe>
```

## Additional Resources
