---
title: "Networking at Conferences"
format: html
toc: true
editor: source
---
## Session Overview

This session offers the opportunity for DSUP students to speak to DURP faculty and senior Ph.D. students to explore how to best navigate conference formal and informal conversation as well as relationships before, during and following conference meetings. A mixed panel discussion (DURP faculty and senior Ph.D. students) will be the best platform for conversation with all participants.

## Before we Meet

Doctoral students on the audience side are encouraged to take some time before the seminar to outline 2-3 questions or discussion topics related to conference attendance, potential challenges and advantages, and practical steps for navigating successful conversations and potential relationships, to engage with the panelist participants.

## After we Meet

Students work together to compile a repository of resources specifically focused on thoughts shared during the session, tips for navigating conversations, and strategies for optimizing professional relationships in academic and non-academic careers.

## Additional Resources
