---
title: "Articulating Your Academic Identity"
format: html
toc: true
editor: source
---
## Session Overview

Advancing to doctoral candidacy is a process focused on solidifying your academic identity. As an early-stage doctoral student, taking classes helps you to define areas of specialization, exposes you to diverse bodies of literature, and helps you to build a methodological repetoire. It is important during this phase that you begin to define and narrate your academic identity - who you are as a scholar, and how your contributions interact with other scholars and bodies of literature.

In this session, we'll spend some time articulating and refining your academic identity. This will serve you well in everything from networking at conferences to preparing for your qualifying exam.

## Before we Meet

- Think about the key identifiers that describe your academic identity.

## When we Meet

We will spend time on three free writing excercises, each taking around 5 minutes. We'll then bring these pieces of free writing together to form three identifying statements.

#### Free Writing Prompts

1. What is your academic origin story? Why are you pursuing a Ph.D. (in planning)?

2. What do you hope to contribute to the field?

3. Who are the main audiences for your work? What story(ies) do you want to tell them?

#### Your Identifying Statements

1. I am a scholar of...

2. I want to make the following contributions to the field:

3. I will know that my has been impactful when...

4. My legacy as an academic will be...


## After we Meet

- Write up your academic identity statements and look at the a few days after our session. Do they still ring true? Modify if neccesary.

## Additional Resources
